### ISSUE TITLE
Site object has no user attribute.

### ISSUE THREAD

**Issue by SimonBerry555** [InteractiveAdvertisingBureau/openrtb2.x#45]
In the documentation, section 3.2.13, the definition of the Site object has no user attribute however in the SimpleBanner example in 6.2.1 the Site object has a user attribute.

I am assuming its the example that is incorrect? Can you please comment?

**Comment by LiruMouse** [comment]
This looks like a bug to me, like the User object was accidentally put inside the Site object.

**Comment by SimonBerry555** [comment]
Was the issue fixed then? (Is there a link to a PR or commit that shows the fix?)
